remote_theme: janczizikow/sleek

# SITE CONFIGURATION
title: Pieter Vandenheede
author: Pieter Vandenheede
description: > # Meta description of Homepage
  Crazy Cool Cloud Stuff
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pvandenheede.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Pieter Vandenheede
  links:
    - https://twitter.com/pvandenheede
    - https://www.linkedin.com/in/pvandenheede
    - https://github.com/pvandenheede

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

#  tagline: Everything is awesome!
hero_img: world.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

#email: pieter.vandenheede@domain.com # email for form submission

twitter_username: pvandenheede # replace with your_twitter_username or comment to remove link from footer
github_username:  pvandenheede # replace with your_github_username or comment to remove link from footer
#instagram_username: wut # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: pvandenheede # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
